import type { BankItem } from "@/lib/types/nexus";

// ─── 51 items transcribed verbatim from QuestionBank.tsv ─────────────────────
// Covers all 5 method families across D1 (production), D2 (production), D4 (production).
// D3 and D5 are intentionally excluded — both are operational_blocked at V1.
// All item_id, dimension_id, facet_id, bank_state, use_status values are preserved exactly.

export const QUESTION_BANK: BankItem[] = [

  // ── D1 PERSONALITY ARCHITECTURE — LIKERT (1-5 Agreement) ─────────────────

  {
    item_id: "NEX-GMB-001",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-CE", dimension_name: "Conscientious Execution",
    facet_id: "D1-CE-DEP", facet_name: "Dependability",
    method_family: "likert", item_format: "statement",
    item_text: "I often struggle to keep my commitments when unexpected tasks come up.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-CE", primary_facet_id: "D1-CE-DEP",
    secondary_dimension_ids: "D5-ED,D5-WS,D4-SR",
    loading_type: "adjacent",
    intended_meaning: "Measures reliability in honoring commitments despite workload changes.",
    prohibited_overlap: "Achievement Drive as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: true,
  },
  {
    item_id: "NEX-GMB-004",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-CE", dimension_name: "Conscientious Execution",
    facet_id: "D1-CE-FT", facet_name: "Follow-Through",
    method_family: "likert", item_format: "statement",
    item_text: "I avoid leaving tasks unfinished at the end of the day.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-CE", primary_facet_id: "D1-CE-FT",
    secondary_dimension_ids: "D5-ED,D5-WS",
    loading_type: "adjacent",
    intended_meaning: "Measures tendency to close out work within the workday.",
    prohibited_overlap: "Adaptability as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-009",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-CE", dimension_name: "Conscientious Execution",
    facet_id: "D1-CE-SD", facet_name: "Self-Discipline",
    method_family: "likert", item_format: "statement",
    item_text: "I resist distractions and stay focused on work until it is done.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-CE", primary_facet_id: "D1-CE-SD",
    secondary_dimension_ids: "D5-ED,D4-SR",
    loading_type: "adjacent",
    intended_meaning: "Measures self-discipline in maintaining focus until task completion.",
    prohibited_overlap: "Achievement Drive as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-011",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-CE", dimension_name: "Conscientious Execution",
    facet_id: "D1-CE-TD", facet_name: "Time Discipline",
    method_family: "likert", item_format: "statement",
    item_text: "I start meetings and work tasks at the scheduled time without delay.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-CE", primary_facet_id: "D1-CE-TD",
    secondary_dimension_ids: "D5-ED",
    loading_type: "adjacent",
    intended_meaning: "Measures punctuality and time discipline for scheduled activities.",
    prohibited_overlap: "General ability explanation",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-013",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-EO", dimension_name: "Exploratory Openness",
    facet_id: "D1-EO-AT", facet_name: "Ambiguity Tolerance",
    method_family: "likert", item_format: "statement",
    item_text: "I find it challenging to stay calm and effective when project details are unclear or incomplete.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-EO", primary_facet_id: "D1-EO-AT",
    secondary_dimension_ids: "D2-DC,D5-AD",
    loading_type: "adjacent",
    intended_meaning: "Measures comfort and effectiveness in handling ambiguity at work.",
    prohibited_overlap: "Confidence image only",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: true,
  },
  {
    item_id: "NEX-GMB-017",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-EO", dimension_name: "Exploratory Openness",
    facet_id: "D1-EO-CRE", facet_name: "Creativity",
    method_family: "likert", item_format: "statement",
    item_text: "I often come up with new ideas to improve how we do our work.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-EO", primary_facet_id: "D1-EO-CRE",
    secondary_dimension_ids: "D2-AR,D5-AD",
    loading_type: "adjacent",
    intended_meaning: "Measures creativity in generating novel ideas at work.",
    prohibited_overlap: "Novelty image only",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-021",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-EO", dimension_name: "Exploratory Openness",
    facet_id: "D1-EO-LA", facet_name: "Learning Appetite",
    method_family: "likert", item_format: "statement",
    item_text: "I look for opportunities to learn new skills or knowledge related to my job.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-EO", primary_facet_id: "D1-EO-LA",
    secondary_dimension_ids: "D3-LD,D2-LA",
    loading_type: "adjacent",
    intended_meaning: "Measures proactive learning appetite in professional settings.",
    prohibited_overlap: "Security Drive as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-025",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-ES", dimension_name: "Emotional Steadiness",
    facet_id: "D1-ES-COMP", facet_name: "Composure",
    method_family: "likert", item_format: "statement",
    item_text: "I often feel unsettled and unclear-headed when unexpected problems arise at work.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-ES", primary_facet_id: "D1-ES-COMP",
    secondary_dimension_ids: "D4-SR,D4-RM",
    loading_type: "adjacent",
    intended_meaning: "Measures ability to maintain composure during workplace disruptions.",
    prohibited_overlap: "Self-Regulation as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: true,
  },
  {
    item_id: "NEX-GMB-031",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-ES", dimension_name: "Emotional Steadiness",
    facet_id: "D1-ES-PS", facet_name: "Pressure Stability",
    method_family: "likert", item_format: "statement",
    item_text: "I maintain steady performance when facing tight deadlines.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-ES", primary_facet_id: "D1-ES-PS",
    secondary_dimension_ids: "D4-RC,D5-LE",
    loading_type: "adjacent",
    intended_meaning: "Measures pressure stability under time constraints.",
    prohibited_overlap: "Confidence image only",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-035",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-ES", dimension_name: "Emotional Steadiness",
    facet_id: "D1-ES-ST", facet_name: "Stress Tolerance",
    method_family: "likert", item_format: "statement",
    item_text: "I handle high-pressure situations without losing my calm.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-ES", primary_facet_id: "D1-ES-ST",
    secondary_dimension_ids: "D4-RC,D4-SR",
    loading_type: "adjacent",
    intended_meaning: "Measures tolerance for stress in demanding scenarios.",
    prohibited_overlap: "Resilience Capacity as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },

  // D1 Integrity Orientation — operational_allowed_with_restrictions
  {
    item_id: "NEX-GMB-037",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IN", dimension_name: "Integrity Orientation",
    facet_id: "D1-IN-ACC", facet_name: "Accountability",
    method_family: "likert", item_format: "statement",
    item_text: "I sometimes fail to follow through on my commitments when unexpected challenges arise.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-IN", primary_facet_id: "D1-IN-ACC",
    secondary_dimension_ids: "D5-ED,D5-LE",
    loading_type: "adjacent",
    intended_meaning: "Measures personal accountability by commitment follow-through under changing conditions.",
    prohibited_overlap: "Conscientious Execution as identity",
    bank_state: "production", use_status: "operational_allowed_with_restrictions",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: true,
  },
  {
    item_id: "NEX-GMB-041",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IN", dimension_name: "Integrity Orientation",
    facet_id: "D1-IN-HON", facet_name: "Honesty",
    method_family: "likert", item_format: "statement",
    item_text: "I clearly communicate facts even when the truth is difficult to share.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-IN", primary_facet_id: "D1-IN-HON",
    secondary_dimension_ids: "D5-CC,D5-JDQ",
    loading_type: "adjacent",
    intended_meaning: "Measures honesty by truthful communication despite difficulty.",
    prohibited_overlap: "Purpose Drive as identity",
    bank_state: "production", use_status: "operational_allowed_with_restrictions",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-049",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IN", dimension_name: "Integrity Orientation",
    facet_id: "D1-IN-RR", facet_name: "Rule Regard",
    method_family: "likert", item_format: "statement",
    item_text: "I adhere to company policies even when enforcement is unlikely.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-IN", primary_facet_id: "D1-IN-RR",
    secondary_dimension_ids: "D5-JDQ,D3-SD",
    loading_type: "adjacent",
    intended_meaning: "Measures rule regard by consistent policy adherence regardless of oversight.",
    prohibited_overlap: "Security Drive as identity",
    bank_state: "production", use_status: "operational_allowed_with_restrictions",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-053",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IO", dimension_name: "Interpersonal Orientation",
    facet_id: "D1-IO-CR", facet_name: "Conflict Restraint",
    method_family: "likert", item_format: "statement",
    item_text: "I keep disagreements professional and avoid personal attacks when conflicts arise.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-IO", primary_facet_id: "D1-IO-CR",
    secondary_dimension_ids: "D4-RM,D4-SR",
    loading_type: "adjacent",
    intended_meaning: "Measures constructive management of interpersonal conflicts.",
    prohibited_overlap: "Passivity as virtue",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-055",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IO", dimension_name: "Interpersonal Orientation",
    facet_id: "D1-IO-EMP", facet_name: "Empathy",
    method_family: "likert", item_format: "statement",
    item_text: "I notice when coworkers are having a hard time and offer support.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-IO", primary_facet_id: "D1-IO-EMP",
    secondary_dimension_ids: "D4-SA,D5-TC",
    loading_type: "adjacent",
    intended_meaning: "Measures awareness and responsiveness to others' emotional states.",
    prohibited_overlap: "Affiliation Drive as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-059",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IO", dimension_name: "Interpersonal Orientation",
    facet_id: "D1-IO-RSP", facet_name: "Respect",
    method_family: "likert", item_format: "statement",
    item_text: "I treat all colleagues with professionalism regardless of their role.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-IO", primary_facet_id: "D1-IO-RSP",
    secondary_dimension_ids: "D4-TC,D5-CC",
    loading_type: "adjacent",
    intended_meaning: "Measures consistent respectful behavior toward others.",
    prohibited_overlap: "Culture fit interpretation",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-065",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-SA", dimension_name: "Social Assertiveness",
    facet_id: "D1-SA-IP", facet_name: "Influence Projection",
    method_family: "likert", item_format: "statement",
    item_text: "I confidently present my recommendations to influence team decisions.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-SA", primary_facet_id: "D1-SA-IP",
    secondary_dimension_ids: "D3-ID,D5-CI",
    loading_type: "adjacent",
    intended_meaning: "Measures the degree to which a person projects confidence to shape team outcomes.",
    prohibited_overlap: "Influence Drive as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-069",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-SA", dimension_name: "Social Assertiveness",
    facet_id: "D1-SA-SC", facet_name: "Social Confidence",
    method_family: "likert", item_format: "statement",
    item_text: "I feel comfortable speaking up in group discussions even when I disagree.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-SA", primary_facet_id: "D1-SA-SC",
    secondary_dimension_ids: "D5-LE,D5-CI",
    loading_type: "adjacent",
    intended_meaning: "Measures confidence in expressing opinions in social settings despite disagreement.",
    prohibited_overlap: "Leadership Expression as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant,invariance",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-073",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-SA", dimension_name: "Social Assertiveness",
    facet_id: "D1-SA-VOICE", facet_name: "Voice",
    method_family: "likert", item_format: "statement",
    item_text: "I openly express my opinions even when they might be unpopular.",
    response_scale: "1-5 Agreement",
    primary_domain_id: "D1", primary_dimension_id: "D1-SA", primary_facet_id: "D1-SA-VOICE",
    secondary_dimension_ids: "D5-LE,D5-CI",
    loading_type: "adjacent",
    intended_meaning: "Measures willingness to voice opinions despite potential disagreement.",
    prohibited_overlap: "Conflict seeking",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },

  // ── D1 FORCED CHOICE (forced_choice_binary) ───────────────────────────────

  {
    item_id: "NEX-GMB-007",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-CE", dimension_name: "Conscientious Execution",
    facet_id: "D1-CE-OV1", facet_name: "Conscientious Execution Overlay 1",
    method_family: "forced_choice", item_format: "paired_statement",
    item_text: "Choose the statement that is more like you at work.",
    option_a: "I prefer to complete tasks thoroughly before moving on to new work.",
    option_b: "I prefer to balance completing tasks with adapting to new priorities as they arise.",
    keyed_answer: "A_or_B",
    response_scale: "forced_choice_binary",
    primary_domain_id: "D1", primary_dimension_id: "D1-CE", primary_facet_id: "D1-CE-OV1",
    loading_type: "adjacent",
    intended_meaning: "Measures preference for thorough task completion versus flexible adaptation.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-008",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-CE", dimension_name: "Conscientious Execution",
    facet_id: "D1-CE-OV2", facet_name: "Conscientious Execution Overlay 2",
    method_family: "forced_choice", item_format: "paired_statement",
    item_text: "Choose the statement that is more like you at work.",
    option_a: "I structure my day with strict time blocks to ensure productivity.",
    option_b: "I keep my schedule flexible to respond quickly to changes in workload.",
    keyed_answer: "A_or_B",
    response_scale: "forced_choice_binary",
    primary_domain_id: "D1", primary_dimension_id: "D1-CE", primary_facet_id: "D1-CE-OV2",
    loading_type: "adjacent",
    intended_meaning: "Measures preference for structured time management versus flexibility.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-023",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-EO", dimension_name: "Exploratory Openness",
    facet_id: "D1-EO-OV1", facet_name: "Exploratory Openness Overlay 1",
    method_family: "forced_choice", item_format: "paired_statement",
    item_text: "Choose the statement that is more like you at work.",
    option_a: "I prefer to quickly decide on tasks even if some details are unclear.",
    option_b: "I prefer to gather more information before making decisions when details are lacking.",
    keyed_answer: "A_or_B",
    response_scale: "forced_choice_binary",
    primary_domain_id: "D1", primary_dimension_id: "D1-EO", primary_facet_id: "D1-EO-OV1",
    loading_type: "adjacent",
    intended_meaning: "Measures preference balance between quick action under ambiguity and cautious information gathering.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-029",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-ES", dimension_name: "Emotional Steadiness",
    facet_id: "D1-ES-OV1", facet_name: "Emotional Steadiness Overlay 1",
    method_family: "forced_choice", item_format: "paired_statement",
    item_text: "Choose the statement that is more like you at work.",
    option_a: "I focus on completing tasks steadily even if I must recover slowly afterward.",
    option_b: "I aim to recover quickly even if it means my focus wavers briefly during tasks.",
    keyed_answer: "A_or_B",
    response_scale: "forced_choice_binary",
    primary_domain_id: "D1", primary_dimension_id: "D1-ES", primary_facet_id: "D1-ES-OV1",
    loading_type: "adjacent",
    intended_meaning: "Measures tradeoff preference between steady composure and rapid recovery under strain.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-057",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IO", dimension_name: "Interpersonal Orientation",
    facet_id: "D1-IO-OV1", facet_name: "Interpersonal Orientation Overlay 1",
    method_family: "forced_choice", item_format: "paired_statement",
    item_text: "Choose the statement that is more like you at work.",
    option_a: "I prefer addressing team conflicts directly to find solutions quickly.",
    option_b: "I focus on maintaining harmony in the team, even if it delays decisions.",
    keyed_answer: "A_or_B",
    response_scale: "forced_choice_binary",
    primary_domain_id: "D1", primary_dimension_id: "D1-IO", primary_facet_id: "D1-IO-OV1",
    loading_type: "adjacent",
    intended_meaning: "Measures preference for direct conflict resolution versus harmony preservation.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-067",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-SA", dimension_name: "Social Assertiveness",
    facet_id: "D1-SA-OV1", facet_name: "Social Assertiveness Overlay 1",
    method_family: "forced_choice", item_format: "paired_statement",
    item_text: "Choose the statement that is more like you at work.",
    option_a: "I prefer to speak up early to shape discussions clearly.",
    option_b: "I prefer to listen first and contribute when I have full information.",
    keyed_answer: "A_or_B",
    response_scale: "forced_choice_binary",
    primary_domain_id: "D1", primary_dimension_id: "D1-SA", primary_facet_id: "D1-SA-OV1",
    loading_type: "adjacent",
    intended_meaning: "Measures preference for proactive versus cautious social assertiveness in communication.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },

  // ── D1 INTEGRITY — SJT (sjt_single_best, operational_allowed_with_restrictions) ──

  {
    item_id: "NEX-GMB-047",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IN", dimension_name: "Integrity Orientation",
    facet_id: "D1-IN-OV1", facet_name: "Integrity Orientation Overlay 1",
    method_family: "sjt", item_format: "scenario_mcq",
    item_text: "You discover a coworker has been improperly billing expenses. What is the strongest response?",
    option_a: "Report the issue promptly to the appropriate supervisor while maintaining confidentiality.",
    option_b: "Discuss the issue only with the coworker to give them a chance to correct it first.",
    option_c: "Ignore it since it is not your responsibility to intervene.",
    option_d: "Confront the coworker publicly to discourage further misconduct.",
    option_e: "Cover for the coworker to maintain team harmony.",
    keyed_answer: "A",
    response_scale: "sjt_single_best",
    primary_domain_id: "D1", primary_dimension_id: "D1-IN", primary_facet_id: "D1-IN-OV1",
    loading_type: "adjacent",
    intended_meaning: "Measures integrity orientation in responding to ethical violations under pressure.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed_with_restrictions",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-048",
    domain_id: "D1", domain_name: "Personality Architecture",
    dimension_id: "D1-IN", dimension_name: "Integrity Orientation",
    facet_id: "D1-IN-OV2", facet_name: "Integrity Orientation Overlay 2",
    method_family: "sjt", item_format: "scenario_mcq",
    item_text: "You are pressured to bend a rule to meet a deadline. What is the strongest response?",
    option_a: "Explain the risks and offer alternative solutions that comply with the rule.",
    option_b: "Bend the rule quietly to ensure the deadline is met on time.",
    option_c: "Ignore the pressure and continue working as usual without changes.",
    option_d: "Appeal directly to upper management to overrule the rule if necessary.",
    option_e: "Delegate the decision to a less experienced team member to avoid conflict.",
    keyed_answer: "A",
    response_scale: "sjt_single_best",
    primary_domain_id: "D1", primary_dimension_id: "D1-IN", primary_facet_id: "D1-IN-OV2",
    loading_type: "adjacent",
    intended_meaning: "Measures integrity orientation by upholding rules under pressure with problem-solving.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed_with_restrictions",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },

  // ── D2 COGNITIVE ARCHITECTURE — COGNITIVE MCQ (cognitive_mcq) ────────────

  {
    item_id: "NEX-GMB-087",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-DC", dimension_name: "Decision Complexity",
    facet_id: "D2-DC-OI", facet_name: "Option Integration",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "You must choose a vendor based on cost, quality, and delivery time. Which factor best indicates the overall best choice?",
    option_a: "Vendor A offers moderate cost, high quality, and on-time delivery.",
    option_b: "Vendor B offers low cost, moderate quality, but delayed delivery.",
    option_c: "Vendor C offers high cost, very high quality, and on-time delivery.",
    option_d: "Vendor D offers low cost, low quality, and on-time delivery.",
    option_e: "Vendor E offers moderate cost, high quality, but delayed delivery.",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-DC", primary_facet_id: "D2-DC-OI",
    secondary_dimension_ids: "D2-SST,D5-JDQ",
    loading_type: "direct",
    intended_meaning: "Measures the ability to integrate multiple option criteria into a balanced decision.",
    prohibited_overlap: "Consensus style as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-090",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-DC", dimension_name: "Decision Complexity",
    facet_id: "D2-DC-PUC", facet_name: "Prioritization Under Constraint",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "You have three urgent tasks but time to complete only one fully. Which should you prioritize?",
    option_a: "The task with the highest impact on revenue.",
    option_b: "The task requested by the most senior leader.",
    option_c: "The task with the nearest deadline.",
    option_d: "The task easiest to complete quickly.",
    option_e: "The task that improves team morale the most.",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-DC", primary_facet_id: "D2-DC-PUC",
    secondary_dimension_ids: "D5-JDQ,D5-ED",
    loading_type: "direct",
    intended_meaning: "Measures prioritization ability under time and resource constraints focusing on impact.",
    prohibited_overlap: "Execution discipline as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-096",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-DC", dimension_name: "Decision Complexity",
    facet_id: "D2-DC-UH", facet_name: "Uncertainty Handling",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "When project data is incomplete, what is the best way to handle the uncertainty?",
    option_a: "Gather additional information before deciding.",
    option_b: "Make a decision based on best available data.",
    option_c: "Delay decision until all data is certain.",
    option_d: "Delegate decision to someone with more expertise.",
    option_e: "Use past similar cases to guide the decision.",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-DC", primary_facet_id: "D2-DC-UH",
    secondary_dimension_ids: "D5-AD",
    loading_type: "direct",
    intended_meaning: "Measures ability to manage uncertainty by seeking more information appropriately.",
    prohibited_overlap: "Confidence under pressure as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-099",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-LA", dimension_name: "Learning Agility",
    facet_id: "D2-LA-AS", facet_name: "Adaptation Speed",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "A team shifts to a new software tool with minimal disruption to their workflow. What is the best explanation?",
    option_a: "They quickly adapted to the new software features and integrated them efficiently.",
    option_b: "They ignored the new tool and continued using old methods.",
    option_c: "They delayed using the new tool until training was complete.",
    option_d: "They delegated the use of the tool to one team member only.",
    option_e: "They reverted back to the former software after initial use.",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-LA", primary_facet_id: "D2-LA-AS",
    secondary_dimension_ids: "D5-AD,D4-RC",
    loading_type: "direct",
    intended_meaning: "Measures the speed at which an individual adapts to new tools or processes in the workplace.",
    prohibited_overlap: "Change appetite as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-102",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-LA", dimension_name: "Learning Agility",
    facet_id: "D2-LA-FI", facet_name: "Feedback Integration",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "After receiving critical feedback on a presentation, what demonstrates effective feedback integration?",
    option_a: "I revise my presentation to address the critiques and improve clarity.",
    option_b: "I defend my original presentation and make no changes.",
    option_c: "I disregard the feedback because it conflicts with my style.",
    option_d: "I blame others for the negative feedback.",
    option_e: "I delay making any changes until more feedback is received.",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-LA", primary_facet_id: "D2-LA-FI",
    secondary_dimension_ids: "D1-IN,D5-AD",
    loading_type: "direct",
    intended_meaning: "Measures the ability to incorporate constructive feedback to improve work outputs.",
    prohibited_overlap: "Humility as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-105",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-LA", dimension_name: "Learning Agility",
    facet_id: "D2-LA-LS", facet_name: "Learning Speed",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "A new software update is released. How quickly do you grasp its main features?",
    option_a: "I learn the features within a day by exploring and testing.",
    option_b: "I postpone learning until a formal training session.",
    option_c: "I read the manual but do not practice the features.",
    option_d: "I rely on others to explain features over time.",
    option_e: "I avoid using the software until necessary.",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-LA", primary_facet_id: "D2-LA-LS",
    secondary_dimension_ids: "D3-LD,D5-AD",
    loading_type: "direct",
    intended_meaning: "Measures speed of learning new technical information through active exploration.",
    prohibited_overlap: "Curiosity as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-111",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-NR", dimension_name: "Numerical Reasoning",
    facet_id: "D2-NR-AN", facet_name: "Applied Numeracy",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "A project requires converting hours worked into billable days. If an employee worked 36 hours and a billable day is 8 hours, how many billable days should be recorded?",
    option_a: "4.5 days",
    option_b: "5 days",
    option_c: "4 days",
    option_d: "3.5 days",
    option_e: "6 days",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-NR", primary_facet_id: "D2-NR-AN",
    secondary_dimension_ids: "D5-JDQ",
    loading_type: "direct",
    intended_meaning: "Measures the ability to apply basic division and unit conversion in workplace contexts.",
    prohibited_overlap: "Conscientiousness as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-114",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-NR", dimension_name: "Numerical Reasoning",
    facet_id: "D2-NR-DPR", facet_name: "Data Pattern Recognition",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "Sales figures for five months are: 120, 135, 150, 165, 180. What is the pattern and the next expected month's sales?",
    option_a: "Increasing by 15 each month; next is 195",
    option_b: "Increasing by 20 each month; next is 200",
    option_c: "Increasing by 10 each month; next is 190",
    option_d: "Decreasing by 15 each month; next is 165",
    option_e: "Constant at 180; next is 180",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-NR", primary_facet_id: "D2-NR-DPR",
    secondary_dimension_ids: "D5-JDQ",
    loading_type: "direct",
    intended_meaning: "Measures recognition of linear numeric trends.",
    prohibited_overlap: "Detail orientation as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-117",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-NR", dimension_name: "Numerical Reasoning",
    facet_id: "D2-NR-NC", facet_name: "Numerical Comparison",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "Which number is larger: 0.75 or 3/4?",
    option_a: "0.75 is larger",
    option_b: "3/4 is larger",
    option_c: "They are equal",
    option_d: "Cannot determine",
    option_e: "Both are less than 0.5",
    keyed_answer: "C",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-NR", primary_facet_id: "D2-NR-NC",
    secondary_dimension_ids: "D5-JDQ",
    loading_type: "direct",
    intended_meaning: "Measures understanding and comparison of decimals and fractions.",
    prohibited_overlap: "General diligence as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-120",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-NR", dimension_name: "Numerical Reasoning",
    facet_id: "D2-NR-QI", facet_name: "Quantitative Inference",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "If the cost per unit is $2 and total cost is $120, how many units were purchased?",
    option_a: "60 units",
    option_b: "240 units",
    option_c: "100 units",
    option_d: "120 units",
    option_e: "80 units",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-NR", primary_facet_id: "D2-NR-QI",
    secondary_dimension_ids: "D5-JDQ",
    loading_type: "direct",
    intended_meaning: "Measures inference of quantity from total and unit cost.",
    prohibited_overlap: "Financial caution as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-135",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-VR", dimension_name: "Verbal Reasoning",
    facet_id: "D2-VR-AE", facet_name: "Argument Evaluation",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "A company claims that increasing remote work options will improve productivity because employees have more flexibility. Which is the safest conclusion?",
    option_a: "Remote work may improve productivity due to increased flexibility, but it is not guaranteed.",
    option_b: "Remote work always leads to higher productivity for all employees.",
    option_c: "Flexibility has no effect on employee productivity.",
    option_d: "Remote work causes distractions that reduce productivity.",
    option_e: "Employees prefer remote work only for personal reasons, not productivity.",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-VR", primary_facet_id: "D2-VR-AE",
    secondary_dimension_ids: "D5-JDQ,D5-CI",
    loading_type: "direct",
    intended_meaning: "Measures ability to evaluate the logical strength of an argument about remote work and productivity.",
    prohibited_overlap: "Debate style as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-141",
    domain_id: "D2", domain_name: "Cognitive Architecture",
    dimension_id: "D2-VR", dimension_name: "Verbal Reasoning",
    facet_id: "D2-VR-INF", facet_name: "Inference",
    method_family: "cognitive_multiple_choice", item_format: "mcq_single",
    item_text: "A report says sales increased after expanding the marketing budget. What is the most reasonable inference?",
    option_a: "Increasing marketing budget likely contributed to higher sales, but other factors may also play a role.",
    option_b: "Sales increase was unrelated to marketing spend.",
    option_c: "Marketing budget alone guarantees sales growth.",
    option_d: "Sales increased due to seasonal trends only.",
    option_e: "Higher sales caused an increase in marketing budget.",
    keyed_answer: "A",
    response_scale: "cognitive_mcq",
    primary_domain_id: "D2", primary_dimension_id: "D2-VR", primary_facet_id: "D2-VR-INF",
    secondary_dimension_ids: "D5-JDQ",
    loading_type: "direct",
    intended_meaning: "Measures ability to infer likely causes from verbal information.",
    prohibited_overlap: "Judgment quality as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },

  // ── D4 INTERPERSONAL AND EMOTIONAL FUNCTIONING — CONTEXTUAL SELF-REPORT ───

  {
    item_id: "NEX-GMB-219",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RC", dimension_name: "Resilience Capacity",
    facet_id: "D4-RC-BBS", facet_name: "Bounce-Back Speed",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "It often takes me a long time to get back to normal productivity after a setback at work.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-RC", primary_facet_id: "D4-RC-BBS",
    secondary_dimension_ids: "D1-ES,D5-AD",
    loading_type: "adjacent",
    intended_meaning: "Measures how fast I recover my work performance after difficulties.",
    prohibited_overlap: "Toughness image only",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: true,
  },
  {
    item_id: "NEX-GMB-221",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RC", dimension_name: "Resilience Capacity",
    facet_id: "D4-RC-END", facet_name: "Endurance",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "I maintain effort on long-term work goals despite challenges and distractions.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-RC", primary_facet_id: "D4-RC-END",
    secondary_dimension_ids: "D1-CE,D3-AD",
    loading_type: "adjacent",
    intended_meaning: "Measures sustained effort on goals over time despite obstacles.",
    prohibited_overlap: "Workaholism",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-224",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RC", dimension_name: "Resilience Capacity",
    facet_id: "D4-RC-PER", facet_name: "Persistence",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "I continue trying to solve problems even when initial attempts fail.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-RC", primary_facet_id: "D4-RC-PER",
    secondary_dimension_ids: "D1-CE,D3-AD",
    loading_type: "adjacent",
    intended_meaning: "Measures my persistence in problem solving after setbacks.",
    prohibited_overlap: "Overwork as virtue",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-228",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RC", dimension_name: "Resilience Capacity",
    facet_id: "D4-RC-ST", facet_name: "Setback Tolerance",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "I handle criticism or setbacks without losing confidence in my work abilities.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-RC", primary_facet_id: "D4-RC-ST",
    secondary_dimension_ids: "D1-ES,D5-AD",
    loading_type: "adjacent",
    intended_meaning: "Measures tolerance of setbacks without confidence loss.",
    prohibited_overlap: "Indifference to feedback",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-232",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RM", dimension_name: "Relationship Management",
    facet_id: "D4-RM-CH", facet_name: "Conflict Handling",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "When disagreements arise, I address them promptly by discussing the issue directly with those involved.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-RM", primary_facet_id: "D4-RM-CH",
    secondary_dimension_ids: "D1-IO,D5-CI",
    loading_type: "adjacent",
    intended_meaning: "Measures proactive handling of conflict through direct communication.",
    prohibited_overlap: "Conflict avoidance as skill",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-235",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RM", dimension_name: "Relationship Management",
    facet_id: "D4-RM-IT", facet_name: "Influence Tone",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "I adjust my communication style to suit the audience's preferences and concerns.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-RM", primary_facet_id: "D4-RM-IT",
    secondary_dimension_ids: "D5-CI,D5-LE",
    loading_type: "adjacent",
    intended_meaning: "Measures adaptability in influence through tone and style adjustments.",
    prohibited_overlap: "Charm only",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-239",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RM", dimension_name: "Relationship Management",
    facet_id: "D4-RM-TB", facet_name: "Trust Building",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "I share relevant information openly to build trust within my team.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-RM", primary_facet_id: "D4-RM-TB",
    secondary_dimension_ids: "D5-TC,D5-LE",
    loading_type: "adjacent",
    intended_meaning: "Measures openness and transparency as trust-building behavior.",
    prohibited_overlap: "Friendliness only",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-241",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-SA", dimension_name: "Self-Awareness",
    facet_id: "D4-SA-EI", facet_name: "Emotional Insight",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "I rarely notice how my feelings affect the way I respond to challenges at work.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-SA", primary_facet_id: "D4-SA-EI",
    secondary_dimension_ids: "D4-SR,D5-JDQ",
    loading_type: "adjacent",
    intended_meaning: "Measures awareness of how personal emotions influence reactions in the workplace.",
    prohibited_overlap: "Introspection as weakness",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: true,
  },
  {
    item_id: "NEX-GMB-248",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-SA", dimension_name: "Self-Awareness",
    facet_id: "D4-SA-SR", facet_name: "Self-Reflection",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "I reflect on my role in team conflicts to improve future interactions.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-SA", primary_facet_id: "D4-SA-SR",
    secondary_dimension_ids: "D4-SR,D5-JDQ",
    loading_type: "adjacent",
    intended_meaning: "Measures purposeful reflection on personal contributions to group dynamics.",
    prohibited_overlap: "Rumination only",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-255",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-SO", dimension_name: "Social Awareness",
    facet_id: "D4-SO-PT", facet_name: "Perspective Taking",
    method_family: "contextual_self_report", item_format: "statement",
    item_text: "I try to see situations from my coworkers' perspectives before responding.",
    response_scale: "1-5 Frequency",
    primary_domain_id: "D4", primary_dimension_id: "D4-SO", primary_facet_id: "D4-SO-PT",
    secondary_dimension_ids: "D1-IO,D5-CI",
    loading_type: "adjacent",
    intended_meaning: "Measures the tendency to adopt others' viewpoints in interpersonal interactions.",
    prohibited_overlap: "Agreeableness as identity",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },

  // ── D4 SJT ────────────────────────────────────────────────────────────────

  {
    item_id: "NEX-GMB-223",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RC", dimension_name: "Resilience Capacity",
    facet_id: "D4-RC-OV1", facet_name: "Resilience Capacity Overlay 1",
    method_family: "sjt", item_format: "scenario_mcq",
    item_text: "You receive critical feedback on a project you led that was not successful. What is the strongest response?",
    option_a: "Listen carefully, acknowledge valid points, and plan improvements based on the feedback.",
    option_b: "Defend your decisions strongly to show confidence in your approach.",
    option_c: "Ignore the feedback and focus on your next task immediately.",
    option_d: "Discuss the feedback with colleagues to find out if others agree before responding.",
    option_e: "Request that your manager handle the feedback discussion to avoid conflict.",
    keyed_answer: "A",
    response_scale: "sjt_single_best",
    primary_domain_id: "D4", primary_dimension_id: "D4-RC", primary_facet_id: "D4-RC-OV1",
    loading_type: "adjacent",
    intended_meaning: "Measures the ability to productively respond to negative feedback and setbacks.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,discriminant",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
  {
    item_id: "NEX-GMB-236",
    domain_id: "D4", domain_name: "Interpersonal and Emotional Functioning",
    dimension_id: "D4-RM", dimension_name: "Relationship Management",
    facet_id: "D4-RM-OV1", facet_name: "Relationship Management Overlay 1",
    method_family: "sjt", item_format: "scenario_mcq",
    item_text: "A team member shares that they feel excluded from important decisions. How should you respond to best manage the relationship?",
    option_a: "Acknowledge their feelings and involve them in upcoming discussions to rebuild trust.",
    option_b: "Explain that decisions are made by leadership and cannot include everyone.",
    option_c: "Suggest they improve communication skills to stay more informed.",
    option_d: "Ignore the comment to avoid escalating tensions.",
    option_e: "Offer to discuss their concerns privately but keep decisions unchanged.",
    keyed_answer: "A",
    response_scale: "sjt_single_best",
    primary_domain_id: "D4", primary_dimension_id: "D4-RM", primary_facet_id: "D4-RM-OV1",
    loading_type: "adjacent",
    intended_meaning: "Measures ability to repair trust and manage inclusion-related conflict constructively.",
    prohibited_overlap: "Dimension overlay should not collapse into image management or generic superiority signaling.",
    bank_state: "production", use_status: "operational_allowed",
    validation_track: "calibration,criterion",
    job_level_overlay: "all_levels", reverse_scored: false,
  },
];

// ─── Lookup helpers ───────────────────────────────────────────────────────────

export function getBankItemById(id: string): BankItem | undefined {
  return QUESTION_BANK.find((item) => item.item_id === id);
}

export function getBankItemsByDomain(domainId: string): BankItem[] {
  return QUESTION_BANK.filter((item) => item.domain_id === domainId);
}

export function getBankItemsByDimension(dimensionId: string): BankItem[] {
  return QUESTION_BANK.filter((item) => item.dimension_id === dimensionId);
}

export function getBankItemsByMethod(method: BankItem["method_family"]): BankItem[] {
  return QUESTION_BANK.filter((item) => item.method_family === method);
}

export const BANK_SUMMARY = {
  total: QUESTION_BANK.length,
  by_method: {
    likert: QUESTION_BANK.filter((i) => i.method_family === "likert").length,
    contextual_self_report: QUESTION_BANK.filter((i) => i.method_family === "contextual_self_report").length,
    forced_choice: QUESTION_BANK.filter((i) => i.method_family === "forced_choice").length,
    cognitive_multiple_choice: QUESTION_BANK.filter((i) => i.method_family === "cognitive_multiple_choice").length,
    sjt: QUESTION_BANK.filter((i) => i.method_family === "sjt").length,
  },
  by_domain: {
    D1: QUESTION_BANK.filter((i) => i.domain_id === "D1").length,
    D2: QUESTION_BANK.filter((i) => i.domain_id === "D2").length,
    D4: QUESTION_BANK.filter((i) => i.domain_id === "D4").length,
  },
};
